apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-NOM PRENOM-MonApplication-backend-ingress
  namespace: dev-NOM PRENOM-MonApplication-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev.monsousdomain.api.flapi.org
      secretName: dev-NOM PRENOM-MonApplication-backend-tls
  rules:
    - host: dev.monsousdomain.api.flapi.org
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: dev-NOM PRENOM-MonApplication-backend-service
                port:
                  number: 3333
