apiVersion: v1
kind: Service
metadata:
  name: dev-NOM PRENOM-MonApplication-backend-service
  namespace: dev-NOM PRENOM-MonApplication-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: dev-NOM PRENOM-MonApplication-backend
