apiVersion: v1
kind: Service
metadata:
  name: staging-NOM PRENOM-MonApplication-backend-service
  namespace: staging-NOM PRENOM-MonApplication-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: staging-NOM PRENOM-MonApplication-backend
